Force data.conftest.file.{dir,name} to be string
Since conftest 0.50.0, due `--show-builtin-errors` enabled by default, tests
started to fail with:

 Error: running verification: run test:
 policy/github/actions/workflows/name.rego:23: eval_type_error: concat:
 operand 2 must be array of strings but got array containing object

Use `sprintf()` to force them to being treated as string.